my:
  servers: [dev.bar.com, foo.bar.com]
logging:
  level:
    com: {senyint: INFO}
script: {groovyPath: groovy\\, javascriptPath: javascript\\}
datasource:
  testa: {url: 'jdbc:oracle:thin:@59.44.27.126:1521:orcl', driver: oracle.jdbc.driver.OracleDriver,
    username: test, password: test}
  testc: {url: 'jdbc:oracle:thin:@59.44.27.126:1521:orcl', driver: oracle.jdbc.driver.OracleDriver,
    username: nmis, password: nmis}
spring:
  datasource: {url: 'jdbc:oracle:thin:@172.16.180.113:1521:orcl', username: test,
    password: test, driver-class-name: oracle.jdbc.driver.OracleDriver}
xmlandjson:
  template: {src: src/main/resources/template/}
task:
  test: {encode: ut, serv: ff, task: test, dataTag: data}
  zscs:
    encode: gbk
    dataTag: DATA
    serv: cancel
    handlerList:
    - {handler: recivestream, config: recivestream}
    - {handler: DATACONVERTMAP, config: recivestream}
    - {handler: database, config: cxb}
    - {handler: convertdata, config: convert}
    - {handler: if, config: if}
    - {handler: branch, config: branch}
    - {handler: database, config: cxc}
    - {handler: convertdata, config: convert1}
    - {handler: GENERATEDATA, config: genconfig}
    task: zscs
handlerConfig:
  genconfig: {templateName: test.xml}
  convert: {scriptFile: convert.groovy, scriptType: groovy, funName: convert}
  convert1: {scriptFile: convert1.groovy, scriptType: groovy, funName: convert}
  cxb: {scriptFile: cxa.js, dataSource: testa, scriptType: javascript, funName: test}
  cxc: {scriptFile: cxc.js, dataSource: testc, scriptType: javascript, funName: test}
  if: {scriptFile: if.js, scriptType: javascript, funName: test}
  branch:
    '01': getdataalist
    '02':
    - {handler: getdatab, config: b}
    - {handler: getdataa, config: a}
handlerListConfig:
  getdataalist:
  - {handler: getdataA, config: b}
  - {handler: getdatab, config: a}
